// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFuCEsyHx55_pYEmh5_Cm72N9GoSqcqU',
    appId: '1:791792611004:web:00e5bdeb0f2737a7e7aab9',
    messagingSenderId: '791792611004',
    projectId: 'fir-a9d40',
    authDomain: 'fir-a9d40.firebaseapp.com',
    storageBucket: 'fir-a9d40.appspot.com',
    measurementId: 'G-EXXCB8VR1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXNdk_AOshSXUNzR-HZph0E1YC3eV7MwA',
    appId: '1:791792611004:android:0aa6ee7fea2eadcae7aab9',
    messagingSenderId: '791792611004',
    projectId: 'fir-a9d40',
    storageBucket: 'fir-a9d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC35Qwa6nUqrbtLeA67l66AVRGjJCoqvjU',
    appId: '1:791792611004:ios:b029cac5b08831b6e7aab9',
    messagingSenderId: '791792611004',
    projectId: 'fir-a9d40',
    storageBucket: 'fir-a9d40.appspot.com',
    iosBundleId: 'com.flutterclass.blocauth',
  );
}
